### ISSUE TITLE
Not able to transfer

### ISSUE THREAD

**Issue by agus-xyz** [MichaelSchwab/iota-commandline-wallet#1]
Everything goes as expected except when I attempt to transfer. I always get an error:

ERROR: Transfer failed. Request Error: COMMAND attachToTangle is not available on this node
{ status: "error", message: "Transfer failed. Request Error: COMMAND attachToTangle is not available on this node"}

I tried changing to different nodes, but always the same result. 
I use Ubuntu 16.04.

Best!

**Comment by MichaelSchwab** [comment]
This happend when the node you send the requests to (configured in the configuration file as provider: ) is configured to not accept your request. Most IOTA nodes have the attachToTangle command disabled. 

One solution would be to setup your own node, or to choose one which is available to the public, sown on http://www.iotasupport.com/gui-lightwallet.shtml or there is also a node configured in the Android wallet.

**Comment by agus-xyz** [comment]
Hi Michael, thanks for your answer. However, I always used public nodes available in the link you shared. Even with the bitfinex node, which is the recommended, I have the same problem. Best.

**Comment by agus-xyz** [comment]
Ok.. so just for me to understand... Most of the public nodes do not allow to make transfers? Is this for real? Why do they then publish them as public nodes for the people to use? People connected to these nodes will not be able to do much use of their iotas, right? Thanks and best.

**Comment by MichaelSchwab** [comment]
Yes you are fully right, to me its also a bit strange, we are working on a solution for this problem! In the first version i included a working node directly into the config file, but I was told not to do so, yes I suggested that someone woukd come up with the problem you described. There is a software calld IOTA Proxy, which might solve the problem, I am currently working to investigate if this could be a solution.

**Comment by GpanosXP** [comment]
Not really, the attachToTangle command is mainly the PoW calculation.
When a public node rejects the command, they are essentially saying "No, I won't do the PoW for you, you have to do that yourself.", which is (imo) the correct behavior.

If you want to do the PoW on the client, you have to include the curl.lib.js and call `curl.overrideAttachToTangle(iotaHandle.api);`
That's what the spammer bots do ;)

**Comment by agus-xyz** [comment]
Makes sense. I am very surprised on the huge performance difference between this wallet and the official one. Thanks to this wallet I was able to start transfering iotas "fluently". Is this because the PoW gets done faster by the server node than the client? Just because the server is 24h running work for the tangle? Thanks.

**Comment by GpanosXP** [comment]
It is because your wallet doesn't do any (hard) work and the server does it for you.
If you are running a full node locally, it _should_ be the same as using the official wallet in light mode and selecting localhost as the provider.

**Comment by agus-xyz** [comment]
Sure, but from my undestanding, my computer should be better than the server doing hard work. Isn't it so?

**Comment by GpanosXP** [comment]
Maybe (I don't know what computer you have).
But the server just replies "ok" and you think that all the work is done, but (afaik) the server hasn't completed the PoW yet, so you get the "illusion" that it's faster.
Or, it could be that the server has some really high-end hardware doing PoW.

**Comment by MichaelSchwab** [comment]
Thats not the entire truth about the speed, currently the PoW is done on the server, but at least the official Android wallet does also offload the PoW to the server. The main speed difference is coming from the address database, in the official wallets all addresses are generated on login, whihc takes multiple seconds per address aon android and one second per address on a average pc. Thats why I implemented a database storing the addresses and states locally.

**Comment by GpanosXP** [comment]
That's interesting, I didn't know. So that speeds up the logging-in part, but should not have any impact on the sending part, right ?

**Comment by MichaelSchwab** [comment]
Exactly!
