### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by paaland** [MichaelSchwab/iota-commandline-wallet#2]
Node v8.6.0.
Cloned your repo.

```
>node my-wallet.js
(node:4176) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'debugLevel' of undefined
(node:4176) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by paaland** [comment]
Ok, I got it. That you have to rename my-wallet.js to match the wallet name in the config is not good. Will make upgrading difficult.

Instead make wallet-name first command line argument like this:
```
node iotawallet.js <wallet-name> [command]
```

**Comment by MichaelSchwab** [comment]
Well, you might have a typo in the config file, which triggers this error. There are still some bugs in 0.7.0 to be fixed hopefully I can release a newer version this weekend. 

That you have to copy the wallets or better symlink them in unix (if you konw how there is also a symlink on Windows), is a design feature. I wanted to use tabcompletion for the walletname keying in as few extra parameters as possible. Alwys typing three parameters over and over agin is not a good solution to me, even on windows alwas typing node as command is annoying!

Hopefully you can understand my point of view. 

Here is a guide how to create a symlink on windows, so after an upgrade you only need to exchange one file (hopefully that works like symlinks on linux, pease test)

https://www.howtogeek.com/howto/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/
