### ISSUE TITLE
How to configure with iotaproxy

### ISSUE THREAD

**Issue by MichaelBakunin** [MichaelSchwab/iota-commandline-wallet#5]
After a lond time fiddling I have iotaproxy running with this message

IOTA proxy server started
POW timeout is set to 15 min
Listening on port 14265
Relaying requests to https://potato.iotasalad.org:80

so I put  'provider': 'http://localhost:14265', in my iota-wallet-config.js

and then do a node ./my-wallet.js Replay WHATEVER....

iotaproxy says "Relaying command findTransactions" 

but  my iota-commandline-wallet comes back with

{ status: "error", message: "Invalid Response: Not Found"}

What do I need to configure to finally get iota-commandline-wallet working with iotaproxy?

**Comment by ckrmml** [comment]
i did it like this

add following to my-wallet.js
- after line 81 where the dependencies get checked:
```Javascript
        var iotaProxy = require('./lib/iotaproxy.js');
```
- this i added right before the iota instance gets configured in lines 121-128:
```Javascript
    // Set IOTAProxy
    try
    {
        // console.log('Node: ' + config.node + ':' + config.port)
        iotaProxy.start(
        {
            host: config.node,
            port: config.port,
            localPort: config.localPort,
            overrideAttachToTangle: config.overrideAttachToTangle,
            timeout: config.timeout
        });
    }
    catch(e)
    {
        error_output('Proxy initialisation failed. ' + e.message);
        return;
    }
```
- change the iota part to:
```Javascript
    var seed = config[cmd_filename].seed;
    if ( seed == "")
    {
        error_output("No seed provided, please enter your seed into the configuration file");
        return;
    }
    else
    {
        try
        {
            // Create IOTA instance directly with provider
            var iota = new IOTA({
          'provider': 'http://localhost:14265'
      });
        }
        catch(e)
        {
            error_output('Iota initialisation failed. ' + e.message);
            return;
        }
    }
```
- change your config to look like this at the top
```Javascript
module.exports = {

    'node': 'WHATEVER NODE TO USE',
    'port': 'PORT OF NODE TO USE',

    'localPort': '14265',
    'overrideAttachToTangle': true,
    'timeout': 15,

    minWeightMagnitude: 14,
    
    "my-wallet": {
    ...
```
- download iota proxy from github, run npm install and copy the whole stuff over to the iota-wallet directory (the lib folder and the node_modules folder). 

You don't need the index.js from iota proxy anymore as it's in the wallet now. works for me. Next step would be to only use proxy when PoW is needed, but meh... another time. If you dont get it, hhit me up, and i could upload the file or request a pull or whatever
