### ISSUE TITLE
Transfer failed. Request Error: COMMAND attachToTangle is not available on this node

### ISSUE THREAD

**Issue by IsThisNickFree** [MichaelSchwab/iota-commandline-wallet#6]
"Transfer failed. Request Error: COMMAND attachToTangle is not available on this node"

How to solve this problem?

**Comment by MichaelSchwab** [comment]
Well thats a problem with the node you selected and configured in the config file as provider.
Some (one a very few) nodes will accept to do the proof of work for you. If a node does not accept to do the proof of work for you you will get the above error message. Solutions are: Find a node which does the proof of work for you, or run your own node, or maybe get IOTA Proxy software ( https://github.com/TimSamshuijzen/iotaproxy ) which does the PoW for you. We are currently working on a wallet which implements PoW but its more difficult then I thought.

**Comment by IsThisNickFree** [comment]
Alright, thank you for your info. I used this node as a provider. https://iotanode.us:443 found here: http://iota.dance/nodes/

it worked afterwards.

Thank you Michael, your wallet saved my funds.
