### ISSUE TITLE
Replay failed. Invalid Bundle provided

### ISSUE THREAD

**Issue by TheFreak17** [MichaelSchwab/iota-commandline-wallet#9]
Hi!
When making a Transfer to my other wallet, the transaction doesn't get confirmed. When I try to Replay it, it says
`{ status: "error", message: "Replay failed. Invalid Bundle provided"}`
although it is the correct address I'm trying to replay. What is wrong?!

**Comment by MichaelSchwab** [comment]
Thats strange, what is the output on screen? You can safely post it here since it is only bundels and addresses.

**Comment by TheFreak17** [comment]
`$ node my-wallet.js R SZNFFWCHJEYJYNUL9KAJDFEIFRNQWEWBQOKUYLHKGCQ9WTWKIHFLFCYXPTVOBLP9MBRLUJXYAFOOWPFYXZBUIPKTNZ
BUNDLE: GRQCSFBHXGCSKYCJT9LHFGLXOJVBFQHACGGZSGHDUJWRBSJNBDNLEKKAJCLYDFXNUHUOIIQEUOAKD9ECC
REPLAY COUNT: 1 CONFIRMED Tx IN BUNDLE: 0 UNCONFIRMED Tx: 4 TAIL: GVVFXQSMMNFXRWYLYDJWWWCKBOLLXHXTCHASJICQVXPFPAJLYWLLKB9RVENNKJBNWBT9YVSXMYJZ99999 Funding: true
Replaying
REPLAY COUNT: 1 CONFIRMED Tx IN BUNDLE: 0 UNCONFIRMED Tx: 4 TAIL: GVVFXQSMMNFXRWYLYDJWWWCKBOLLXHXTCHASJICQVXPFPAJLYWLLKB9RVENNKJBNWBT9YVSXMYJZ99999 Funding: true
{ status: "error", message: "Replay failed. Invalid Bundle provided"}`

**Comment by MichaelSchwab** [comment]
Thanks for your info, I checked it on my machine getting the same error, but have currently no idea.
Looks like it is somewhere in iota.lib.js  The given tail transaction is correct.

**Comment by MichaelSchwab** [comment]
This is the function which makes problems
        if (!Utils.isBundle(bundle)) {

            return callback(new Error("Invalid Bundle provided"))

its in utils.js  and smehow it retunes false despite og that the bundle which is given to the function looks ok

**Comment by MichaelSchwab** [comment]
Finally it looks like a problem with the signature to me, thats where it exits ...

**Comment by TheFreak17** [comment]
I can only find the lines you mentioned in the file “iota.js”. But since that file is in the folder of the “IOTA Wallet” (the “official” IOTA wallet I installed before and didn't work out but still left on the computer), I think it shouldn't be accounted for this problem. Where can I find the file “utils.js” you mentioned?
So sending Iota works completely fine on your computer and you don't get the error on replaying?
What do you mean by signature? Any idea what I can do to make transactions work?
One more info: two days before the snapshot last Sunday I tried to transfer 10 and another time 100 Iota. Both transactions kept being “pending” (on thetangle.org) until the snapshot. So they did not get transferred. (I tried to send 100 Iota instead of just 10 because I thought maybe it doesn't get transferred because 10 Iota is too little of an amount to send.)

**Comment by MichaelSchwab** [comment]
The utils.js is in the modules you downloaded by npm install it is part of the iota javascript library,
so well, I am not sure where the problem is, since the signature of your transaction seems to be invalid and so the transaction will never be confirmed.
